language: objective-c
cache: cocoapods
osx_image: xcode9.2
notifications:
  email:
    on_success: never
    on_failure: never
before_install:
- fastlane update_fastlane
- pod repo update
script: fastlane ios test
