default_platform :ios

platform :ios do
  before_all do
    cocoapods    
  end

  desc "Runs all the tests"
  lane :test do
    swiftlint
    scan(
      skip_slack: true, 
      scheme: "OBankingConnector-iOS"
    )
  end
end